### ISSUE TITLE
Loader can't find install location on Linux

### ISSUE THREAD

**Issue by JaredFeeney** [AstroTechies/astro_modloader#13]
In the case of running the loader through WINE, it can't find the install location of Astroneer through Steam. An option to choose custom install location or Linux compatibility of some sort would be really nice.

**Comment by konsti219** [comment]
Why would you run the modlaoder through wine when it has a native Linux version?

**Comment by JaredFeeney** [comment]
Where can I find the Linux version? In the releases tab there is only an EXE, It's not found in my system package manager or Flathub, and a I can't find any info online for a native mod loader.

**Comment by konsti219** [comment]
https://discord.com/channels/774729322674126858/1073719803677773935/1140676311468228708

**Comment by JaredFeeney** [comment]
Some sort of readme for the Github page with information like this would save you all some headaches. I'm sorry, but Discord is a shit way to disseminate information like this.

**Comment by benjamin-kirkbride** [comment]
@konsti219 it seems the build instructions are no longer accessible on Discord.
