### ISSUE TITLE
Windows says this has a trojan is normal?

### ISSUE THREAD

**Issue by Dev-Zeta** [AstroTechies/astro_modloader#14]

**Comment by konsti219** [comment]
Why did you have to open a fucking issue for this? Couldn't you just have asked in the discord?

And yes, this is totally normal because this program does not have a massive user base.

**Comment by localcc** [comment]
Please be nicer to people.

**Comment by Dev-Zeta** [comment]
> Please be nicer to people.

dont worry i can understand why he reacted like that i should apologise, so sorry

**Comment by konsti219** [comment]
I definitely overreacted, sorry.
