### ISSUE TITLE
Please re-add the feature to select a custom game path.

### ISSUE THREAD

**Issue by Vieh1** [AstroTechies/astro_modloader#17]
I cannot get the mod loader to work with my game. I am using the EXE with Wine on Ubuntu. The game is saved on my PC, but the mod loader cannot find it. I have tried putting it into the Proton instalation and it still does not see it. I have tried running it with SteamTinkerLaunch and it does not see it.

Is there a workaround for this?

Best,
Vieh

**Comment by Vieh1** [comment]
Never mind, found instructions for linux on the discord.

**Comment by Vieh1** [comment]
> Could you please detail how you fixed it? [@Vieh1](https://github.com/Vieh1)

There's someone who posted a functioning file somewhere on the discord server. It has no extension. Just search the server for "@BloodRedRage" and you should find it

**Comment by konsti219** [comment]
> Could you please detail how you fixed it? [@Vieh1](https://github.com/Vieh1)

Build the modloader for Linux
