### ISSUE TITLE
Unable to drag an drop

### ISSUE THREAD

**Issue by Dinhero21** [AstroTechies/astro_modloader#18]
My System config:
```
             .',;::::;,'.                 dinhero21@fedora
         .';:cccccccccccc:;,.             ----------------
      .;cccccccccccccccccccccc;.          OS: Fedora Linux 40 (KDE Plasma) x86_64
    .:cccccccccccccccccccccccccc:.        Host: X570 Phantom Gaming 4
  .;ccccccccccccc;.:dddl:.;ccccccc;.      Kernel: Linux 6.10.6-200.fc40.x86_64
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.     Uptime: 2 days, 18 mins
.:ccccccccccccc;KMMc;cc;xMMc;ccccccc:.    Packages: 2364 (rpm), 19 (flatpak), 3 (snap)
,cccccccccccccc;MMM.;cc;;WW:;cccccccc,    Shell: zsh 5.9
:cccccccccccccc;MMM.;cccccccccccccccc:    Display (SyncMaster): 1920x1080 @ 60 Hz in 7″ [External]
:ccccccc;oxOOOo;MMM000k.;cccccccccccc:    DE: KDE Plasma 6.1.4
cccccc;0MMKxdd:;MMMkddc.;cccccccccccc;    WM: KWin (Wayland)
ccccc;XMO';cccc;MMM.;cccccccccccccccc'    WM Theme: Breeze
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;     Theme: Breeze (Dark) [Qt], Breeze [GTK3]
ccccc;0MNc.ccc.xMMd;ccccccccccccccc;      Icons: breeze-dark [Qt], breeze-dark [GTK3/4]
cccccc;dNMWXXXWM0:;cccccccccccccc:,       Font: Noto Sans (10pt) [Qt], Noto Sans (10pt) [GTK3/4]
cccccccc;.:odl:.;cccccccccccccc:,.        Cursor: breeze (24px)
ccccccccccccccccccccccccccccc:'.          Terminal: konsole 24.8.0
:ccccccccccccccccccccccc:;,..             Terminal Font: Monospace (10pt)
 ':cccccccccccccccc::;,.                  CPU: AMD Ryzen 7 5800X (16) @ 3.80 GHz
                                          GPU: NVIDIA GeForce RTX 4070 [Discrete]
                                          Memory: 14.22 GiB / 31.26 GiB (45%)
                                          Swap: 512.00 KiB / 8.00 GiB (0%)
                                          Disk (/): 78.17 GiB / 1.82 TiB (4%) - btrfs
                                          Local IP (enp3s0): 192.168.0.137/24
                                          Locale: en_US.UTF-8
```

When dragging and dropping files from [Dolphin](https://apps.kde.org/dolphin/) to Astroneer Modloader (`astro_modloader`, compiled following [these](https://github.com/AstroTechies/astro_modloader?tab=readme-ov-file#linux) instructions), the cursor style does not change and nothing happends.

**Comment by Dinhero21** [comment]
(If it does not already exist,) I suggest another way of adding/removing/configuring mods, such as a CLI, so that graphical issues can not impossibilitate modding the game.

**Comment by konsti219** [comment]
https://github.com/rust-windowing/winit/issues/1881

You can just drop .pak files in the Saved/Mods folder.

**Comment by Dinhero21** [comment]
> [rust-windowing/winit#1881](https://github.com/rust-windowing/winit/issues/1881)
> 
> You can just drop .pak files in the Saved/Mods folder.

Couldn't locate, running
```
find \
~/Documents/GitHub/astro_modloader \
~/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/ASTRONEER \
~/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/361420 \
-iname "Mods"
```
returns nothing.

Maybe they don't generate until the first mod installed?

**Comment by sschr15** [comment]
The directory is generated at `~/.local/share/Astro/Saved/Mods` (or if `XDG_DATA_HOME` is set, `$XDG_DATA_HOME/Astro/Saved/Mods`). The `unreal_mod_manager` crate [defines](https://github.com/AstroTechies/unrealmodding/blob/main/unreal_mod_manager/src/background_work.rs#L135-L140) the mod directory as `BaseDir::data_local_dir()`/(game name)/Saved/Mods.

**Comment by Dinhero21** [comment]
> The directory is generated at `~/.local/share/Astro/Saved/Mods` (or if `XDG_DATA_HOME` is set, `$XDG_DATA_HOME/Astro/Saved/Mods`). The `unreal_mod_manager` crate [defines](https://github.com/AstroTechies/unrealmodding/blob/main/unreal_mod_manager/src/background_work.rs#L135-L140) the mod directory as `BaseDir.data_local_dir`/(game name)/Saved/Mods.

It worked! Thank you very much!

I feel like this should be more well documented but unsure where (maybe a note in this project's README? "You can also manually move pak files into `~/.local/share/Astro/Saved/Mods/`")
