### ISSUE TITLE
astroneermods.space down

### ISSUE THREAD

**Issue by equalisysdev** [AstroTechies/astro_modloader#21]
So i cant download nor update my mods

**Comment by konsti219** [comment]
Not a modloader issue

**Comment by Famous5000** [comment]
_You might want to update the thing to use a forked site if you haven't already:_

https://astromod.space

that's the new one for now. Lets hope the original site can be recovered at some point...

**Comment by konsti219** [comment]
@Famous5000 That site is in violation of my copyright.
