### ISSUE TITLE
Unable to load mods by drag and drop.

### ISSUE THREAD

**Issue by Pherex** [AstroTechies/astro_modloader#3]
After first loading the modloader, I dragged and dropped the .pak files for the mods.
At first it couldn't download them but then I restarted it with admin.
But every mod is flagged with an error whenever the Modloader starts up.
I've pasted a snippet of the log file

> [WARN  b59\2d2951f\unreal_modloader\src\mod_processing\pakfile_reading.rs:107] Failed to read pak file "000-AdapterMod-0.3.0_P.pak", error: mod: "000-AdapterMod-0.3.0_P.pak", UnrealPak error: IO error: An attempt was made to move the file pointer before the beginning of the file. (os error 131), deleting...
[WARN  b59\2d2951f\unreal_modloader\src\mod_processing\pakfile_reading.rs:107] Failed to read pak file "000-AstroNav-1.0.2_P.pak", error: mod: "000-AstroNav-1.0.2_P.pak", UnrealPak error: IO error: An attempt was made to move the file pointer before the beginning of the file. (os error 131), deleting...
[WARN  b59\2d2951f\unreal_modloader\src\mod_processing\pakfile_reading.rs:107] Failed to read pak file "000-DescriptionsPlus-0.1.4_P.pak", error: mod: "000-DescriptionsPlus-0.1.4_P.pak", UnrealPak error: IO error: An attempt was made to move the file pointer before the beginning of the file. (os error 131), deleting...
[WARN  b59\2d2951f\unreal_modloader\src\mod_processing\pakfile_reading.rs:107] Failed to read pak file "000-RocketLauncher-1.0.0_P.pak", error: mod: "000-RocketLauncher-1.0.0_P.pak", UnrealPak error: IO error: An attempt was made to move the file pointer before the beginning of the file. (os error 131), deleting...
[WARN  b59\2d2951f\unreal_modloader\src\mod_processing\pakfile_reading.rs:107] Failed to read pak file "000-SnailBuffTime-1.0.2_P.pak", error: mod: "000-SnailBuffTime-1.0.2_P.pak", UnrealPak error: IO error: An attempt was made to move the file pointer before the beginning of the file. (os error 131), deleting...
[WARN  b59\2d2951f\unreal_modloader\src\mod_processing\pakfile_reading.rs:107] Failed to read pak file "000-Supercondenser-0.1.1_P.pak", error: mod: "000-Supercondenser-0.1.1_P.pak", UnrealPak error: IO error: An attempt was made to move the file pointer before the beginning of the file. (os error 131), deleting...
[WARN  b59\2d2951f\unreal_modloader\src\mod_processing\pakfile_reading.rs:107] Failed to read pak file "001-MoreTradables-1.0.1_P.pak", error: mod: "001-MoreTradables-1.0.1_P.pak", UnrealPak error: IO error: An attempt was made to move the file pointer before the beginning of the file. (os error 131), deleting...

**Comment by localcc** [comment]
Is your user account an administrator account?
Could you send the contents of the %LOCALAPPDATA%/Astro folder?

**Comment by Pherex** [comment]
[Astro.zip](https://github.com/AstroTechies/astro_modloader/files/9584991/Astro.zip)

admin account

**Comment by Pherex** [comment]
[modloader_log.txt](https://github.com/AstroTechies/astro_modloader/files/9586570/modloader_log.txt)

**Comment by localcc** [comment]
Clear %LOCALAPPDATA%/Astro/Saved/Mods folder and try with the latest modloader release, there will be more debugging information.

**Comment by Pherex** [comment]
[modloader_log.txt](https://github.com/AstroTechies/astro_modloader/files/9590624/modloader_log.txt)

**Comment by localcc** [comment]
Which operating system version do you have? Preferrably a `winver` screenshot

**Comment by Pherex** [comment]
![image](https://user-images.githubusercontent.com/3982099/190861748-b189bde0-4268-4964-ac33-34bd40cfaa0c.png)

**Comment by localcc** [comment]
Only Windows 10 and higher are supported
