### ISSUE TITLE
UnrealPak error: IO error: failed to fill whole buffer

### ISSUE THREAD

**Issue by sn1pp** [AstroTechies/astro_modloader#5]
my friend tried adding new planet using UE4, but after packing and adding mod this message came up:
![image-4](https://user-images.githubusercontent.com/79652963/207353820-67631728-2591-4b50-b27a-055bd634788e.png)

log file:
[modloader_log.txt](https://github.com/AstroTechies/astro_modloader/files/10218611/modloader_log.txt)

any fix?

**Comment by localcc** [comment]
The file is invalid because it doesn't contain a metadata.json. The error message will be fixed though.
