### ISSUE TITLE
[Bug] "Astro/Content/Maps/Staging_T2_PackedPlanets_Switch.umap" not found

### ISSUE THREAD

**Issue by misaka10843** [AstroTechies/astro_modloader#9]
I tested multiple mods and they all showed the error message "Integration work error: Integrator error: Asset 'Astro/Content/Maps/Staging_T2_PackedPlanets_Switch.umap' not found". Does this seem to be related to the Astro beta version?
![image](https://github.com/AstroTechies/astro_modloader/assets/69132853/b2ea527b-d452-4ae7-aa9c-770075074b9f)

[modloader_log.txt](https://github.com/AstroTechies/astro_modloader/files/11987223/modloader_log.txt)

**Comment by konsti219** [comment]
What version of astroneer are you using?

**Comment by misaka10843** [comment]
> What version of astroneer are you using?

My Astroneer version is 1.2.9.0 in Exo_ Flight_ Test Channel

**Comment by konsti219** [comment]
That version is over 3 years old. In Steam select `No Beta`.
